server:
  port: 8400

spring:
  application:
    name: user-center
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: 192.168.12.103
    port: 5672
    username: guest
    password: guest
  zipkin:
      base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

