eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 5000

spring:
  application:
    name: gateway-center
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: 192.168.12.103
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://localhost:9411



zuul:
  routes:
    user-center:
      path: /user/**
      serviceId: user-center

